### ISSUE TITLE
Lab2 замечания 1

### ISSUE THREAD

**Issue by Andrewbooq** [ArtemH2004/PoolThreads#2]
1 Это из Си, какая директива препроцессора для этого в плюсах?
```
#ifndef THREADPOOL_H
#define THREADPOOL_H
```
2 The rule of zero, the rule of  five о чём гласит?
3 Везде использовать unique_lock не рационально, что еще есть? В чём между ними разница и какой нужно в каком случае применять?
4 Что будет, если 2 раза позвать worker.join(); ? Что нужно сделать чтобы исключить повторный вызов join?
5 Условия завершения потока в worker неверное. Если мы хотим завершить все потоки и уничтожить объект, мы не сможем это сделать. Игнарируя наше желание ThreadPool будет продолжать выгребать из очереди задачи и приступать к их выполнению.
6 writeFile в качестве примера отлично НО, делать это из разных потоков нужно аккуратно. Что нужно сделать, чтобы из разных потоков можно было проводить операции чтения/записи?
7 `<<` не является threadsafe. Нужно использовать другой подход (речь про вывод в консоль). Сейчас это не страшно, но см. след. пункт
8 Добавить user-friendly к своему приложению. Человек, не знакомый  кодом, должен запустить и понять что происходит: что за приложение запущено, сколько тредов, зачем они, как они запущены, чего ждем, куда результат поместим,.....
9 Добавить Makefile для сборки под Linux, собрать, например, на Ubuntu. Запустить и сравнить результат с Windows. Подумать, насколько сложно было портировать с Windows на Linux?
10 this_thread::sleep_for(chrono::seconds(10)); для начала пойдет, но слипов в конечном приложении не должно быть, здесь, возможно, нужно что-то другое придумать, чтобы работало корректно.

**Comment by Andrewbooq** [comment]
Кокой бранч смотреть?

**Comment by ArtemH2004** [comment]
improveMistakes и makefile
Я их разделил просто, чтобы не сливалось

**Comment by Andrewbooq** [comment]
1 Исправлено
2 > rule of five - правило пяти предполагает, что нам нужно определить конструктор копирования, оператор присваивания, перемещающий конструктор, перемещающий оператор присваивания и деструктор.
Немного не точно, но допустим. И где же все они в коде? Если не разберешься завтра на лабу приходи, расскажу.
Послушал бы на лекции, сразу бы сделал. 
3 Исправлено А еще lock_guard занимает меньше памяти и работает быстрее, и его предпочтительнее использовать, если нам его функционала достаточно.
4 Исправлено
5 Условия завершения потока в worker неверное. Если мы хотим завершить все потоки и уничтожить объект, мы не сможем это сделать. Игнарируя наше желание ThreadPool будет продолжать выгребать из очереди задачи и приступать к их выполнению.
6 Не уверен, что объект `static mutex fileMutex;` объявленный вот так - это один и тот же объект. Так работает для нескольких экземпляров класса, во всех будет один и тот же мембер, если он статик. В Сишной нотации static означает совсем другое. Я бы предложил сделать его хотя бы глобальным как `mutex consoleMutex;` Хотя вроде в файл пишется правильно...
7 Исправлено, решение годится. Но вообще, можно printf использовать, она threadsafe
8 Исправлено
9 В Makefile `-pthread` для чего добавлен? И когда он нужен? Сегодня же рассказывал...
10 Исправлено.
Под Linux собирается и работает.

Что не нравится:
- Нет ни одного code style где было бы разрешено писать две инструкции на одной строке. Речь про это, например `if (worker.joinable()) worker.join();` или это `if (stop && tasks.empty()) return;`, лямбду тоже похорошему разнести по строкам, согласно стилю остального кода - `{` на строке предыдущей инструкции, следующая инструкция с новой строки.
- Приложение пишет в файл слишком быстро, нужно или писать побольше данных, или еще что-то делать.
- Не нравится этот вывод:
```
On your computer the number of threads = 8
Tasks and the threads in which they were executed are recorded in the file 'output.txt'
Tasks remaining in the queue: 2
Tasks remaining in the queue: 1
Tasks remaining in the queue: 0
Tasks remaining in the queue: 0
Tasks remaining in the queue: 0
Tasks remaining in the queue: 0
Tasks remaining in the queue: 0
Tasks remaining in the queue: 0
Tasks remaining in the queue: 0
Tasks remaining in the queue: 0
```
Почему Tasks remaining in the queue 0 так много раз нули? 
Что нам дает эта информация, если мы говорим про отладку? Такое ощущение, что этот вывод надо перенести туда, где мы выгребаем из очереди и делаем декремент tasksCount, а не после завершения задачи.

**Comment by Andrewbooq** [comment]
Кстати, в Makefile все нефайловые цели (all и clean являются нефайловыми) нужно оборачивать в .PHONY
```
.PHONY: all clean
```

**Comment by ArtemH2004** [comment]
Здравствуйте, исправил 5), 6), 9) 

code style поправлен

Добавлено 100 задач, чтобы программа выполнялась не так быстро

Вывод исправлен, при отсутствии задач в очереди будут выводится не нули, а строка "Queued tasks are complete"

**Comment by Andrewbooq** [comment]
Здравствуй, 2 тоже надо исправить

**Comment by ArtemH2004** [comment]
Здравствуйте, исправил

**Comment by ArtemH2004** [comment]
Здравствуйте, а что именно не работает в Makefile? Просто у меня все работает,  в прошлый раз возможно проблема была с отступами в некоторый строках, там почему-то вместо отступа tab пробел стоял. Возможно, github как-то файл изменил.

**Comment by Andrewbooq** [comment]
Ох уж это вечное противостояние QA vs Developers: QA кричат - у вас ничего не работает, Developers отвечают, у нас работает, давайте логи и шаги, как повторить =))).
Давай разбираться. Не буду полностью говрить что не так, опишу немного как получить.
Я хочу выполнить две команды, чтобы пересобрать всё с нуля:
`make clean` и затем `make all`
и вот что я вижу
```
$ make all
make: Nothing to be done for 'all'.
```
Я здесь ожидал увидеть кое-что другое.

**Comment by Andrewbooq** [comment]
> Возможно, github как-то файл изменил.

Нет, невозможно. В разных IDE tab может по разному интерпретироваться, либо табуляция либо N пробелов. Ты мог частично в MSVS поправить и в блокноте, например, и один вставил табуляцию, другой 4 пробела.

**Comment by ArtemH2004** [comment]
Здравствуйте. Разнес лабы по веткам. 
В lab2 я перенес пул потоков с Makefile.
В lab3 добавил реализацию WinApi и Pthread.

**Comment by Andrewbooq** [comment]
2 лаба - можно сдавать.
