### ISSUE TITLE
Lab3 замечания

### ISSUE THREAD

**Issue by Andrewbooq** [ArtemH2004/PoolThreads#8]
1 Ой как вы не любите проверять передаваемые значения. ThreadPool* pool и зразу обращение по указателю. А если он ноль?

2 HANDLE thread = .. и сразу workers.push_back(thread); А если поток не создался? где диагностическое сообщение с кодом ошибки?
pthread тоже самое.

3
```
#if defined (_WIN32) || defined (_WIN64)
...
#else // На маке можно запускать? соберется?
```

Где диагностическое сообщение, если запущена сборка на неподдерживаемой платформе?

В остальном вроде норм выглядит

**Comment by ArtemH2004** [comment]
Здравствуйте, исправил.

**Comment by Andrewbooq** [comment]
В деструкторе в цикле WaitForSingleObject выглядит кривенько, там бы WaitForMultipleObjects, но не критично.

**Comment by Andrewbooq** [comment]
В остальном всё ОК, сдавай.
